//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АптекаEntities : DbContext
    {
        public АптекаEntities()
            : base("name=АптекаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Заказ_Препарат> Заказ_Препарат { get; set; }
        public virtual DbSet<Изготовитель> Изготовитель { get; set; }
        public virtual DbSet<Контактные_данные> Контактные_данные { get; set; }
        public virtual DbSet<Личные_данные> Личные_данные { get; set; }
        public virtual DbSet<Назначение> Назначение { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставка> Поставка { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Препарат> Препарат { get; set; }
        public virtual DbSet<Препарат_Поставка> Препарат_Поставка { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Социальная_карта> Социальная_карта { get; set; }
    }
}
