//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Заказ_Препарат = new HashSet<Заказ_Препарат>();
        }
    
        public int Код_заказа { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<int> Код_социальной_карты { get; set; }
        public int Количество_препаратов { get; set; }
        public decimal Стоимость { get; set; }
        public System.DateTime Дата_исполнения { get; set; }
        public System.DateTime Время_исполнения { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Социальная_карта Социальная_карта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_Препарат> Заказ_Препарат { get; set; }
    }
}
