//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Код_сотрудника { get; set; }
        public int Код_должности { get; set; }
        public int Код_контактных_данных { get; set; }
        public int Код_пользователя { get; set; }
        public int Код_личных_данных { get; set; }
        public System.DateTime Дата_приёма_на_работу { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Контактные_данные Контактные_данные { get; set; }
        public virtual Личные_данные Личные_данные { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
